# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6862e3fdcedad372952ef2325e55f5f6902859141fc389679abb8de0cc878dce190160ac3491f03154b554c67def3fb9a7db2008011b18611d4972551c4a6267

test:
  secret_key_base: 1dfcb3cc2b5315561b02085f07419b928fc24591cbc51121a06e1034c1c5b7addfa9a6897234ef63a64298554bdae9535344a99225121009686d04f04858caa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
